const fakeDB = [
    {
        "firstConnections": [],
        "temporaryConnections": [],
        "healthStatus": 4,
        "healthStatusOnLastCheck": 4,
        "creationDate": "2020-10-29T00:30:18.000Z",
        "_id": "5f9a0da52ed12012457c43f1",
        "firstName": "The Macho Man",
        "lastName": "Randy Savage",
        "email": "machoman@gmail.com",
        "__v": 0
    },
    {
        "firstConnections": [],
        "temporaryConnections": [],
        "healthStatus": 4,
        "healthStatusOnLastCheck": 4,
        "creationDate": "2020-10-29T00:30:18.000Z",
        "_id": "5f9a0dc22ed12012457c43f2",
        "firstName": "Hulk",
        "lastName": "Hogan",
        "email": "hhbrother@gmail.com",
        "__v": 0
    },
    {
        "firstConnections": [],
        "temporaryConnections": [],
        "healthStatus": 4,
        "healthStatusOnLastCheck": 4,
        "creationDate": "2020-10-29T00:30:18.000Z",
        "_id": "5f9a0dd32ed12012457c43f3",
        "firstName": "Michael",
        "lastName": "Fox",
        "email": "malf@gmail.com",
        "__v": 0
    },
    {
        "firstConnections": [],
        "temporaryConnections": [],
        "healthStatus": 4,
        "healthStatusOnLastCheck": 4,
        "creationDate": "2020-10-29T00:30:18.000Z",
        "_id": "5f9a0df42ed12012457c43f4",
        "firstName": "Chika",
        "lastName": "Fujiwara",
        "email": "chikaf@gmail.com",
        "__v": 0
    },
    {
        "firstConnections": [],
        "temporaryConnections": [],
        "healthStatus": 4,
        "healthStatusOnLastCheck": 4,
        "creationDate": "2020-10-29T00:30:18.000Z",
        "_id": "5f9a0e132ed12012457c43f5",
        "firstName": "Kaguya",
        "lastName": "Shinomiya",
        "email": "kaguyas@gmail.com",
        "__v": 0
    },
    {
        "firstConnections": [],
        "temporaryConnections": [],
        "healthStatus": 4,
        "healthStatusOnLastCheck": 4,
        "creationDate": "2020-10-29T00:30:18.000Z",
        "_id": "5f9a0e5b2ed12012457c43f6",
        "firstName": "Ai",
        "lastName": "Hayasaka",
        "email": "hayasakaai@gmail.com",
        "__v": 0
    },
    {
        "firstConnections": [],
        "temporaryConnections": [],
        "healthStatus": 4,
        "healthStatusOnLastCheck": 4,
        "creationDate": "2020-10-29T00:30:18.000Z",
        "_id": "5f9a0e6c2ed12012457c43f7",
        "firstName": "Tristen",
        "lastName": "Daab",
        "email": "tdab@gmail.com",
        "__v": 0
    },
    {
        "firstConnections": [],
        "temporaryConnections": [],
        "healthStatus": 4,
        "healthStatusOnLastCheck": 4,
        "creationDate": "2020-10-29T00:30:18.000Z",
        "_id": "5f9a0e882ed12012457c43f8",
        "firstName": "Miyuki",
        "lastName": "Shirogane",
        "email": "miyukis@gmail.com",
        "__v": 0
    },
    {
        "firstConnections": [],
        "temporaryConnections": [],
        "healthStatus": 4,
        "healthStatusOnLastCheck": 4,
        "creationDate": "2020-10-29T00:30:18.000Z",
        "_id": "5f9a0ea92ed12012457c43f9",
        "firstName": "Yu",
        "lastName": "Ishigami",
        "email": "ishigamiyu@gmail.com",
        "__v": 0
    },
    {
        "firstConnections": [],
        "temporaryConnections": [],
        "healthStatus": 4,
        "healthStatusOnLastCheck": 4,
        "creationDate": "2020-10-29T00:30:18.000Z",
        "_id": "5f9a0eba2ed12012457c43fa",
        "firstName": "Dan",
        "lastName": "Gheesling",
        "email": "dannyg@gmail.com",
        "__v": 0
    },
    {
        "firstConnections": [],
        "temporaryConnections": [],
        "healthStatus": 4,
        "healthStatusOnLastCheck": 4,
        "creationDate": "2020-10-29T00:30:18.000Z",
        "_id": "5f9a0ed72ed12012457c43fb",
        "firstName": "Ryab",
        "lastName": "Letourneau",
        "email": "northernlion@gmail.com",
        "__v": 0
    },
    {
        "firstConnections": [],
        "temporaryConnections": [],
        "healthStatus": 4,
        "healthStatusOnLastCheck": 4,
        "creationDate": "2020-10-29T00:30:18.000Z",
        "_id": "5f9a0ee82ed12012457c43fc",
        "firstName": "Luna",
        "lastName": "Letourneau",
        "email": "lunal@gmail.com",
        "__v": 0
    },
    {
        "firstConnections": [],
        "temporaryConnections": [],
        "healthStatus": 4,
        "healthStatusOnLastCheck": 4,
        "creationDate": "2020-10-29T00:30:18.000Z",
        "_id": "5f9a0efd2ed12012457c43fd",
        "firstName": "Kanye",
        "lastName": "West",
        "email": "kwestbeatz@gmail.com",
        "__v": 0
    }
];

module.exports = fakeDB;